<?include_once Config::LAYOUT_DIR."userInfo".Config::LAYOUT_TYPE;?>
<?=Menu::getMenu()?>
<div class="wrap">
    <div class="innerWrap">
        <div class="slide_side">
            <div id="LContainer" class="container-fluid">
                <h2 class="info">Candidates</h2>
                
                <div id="somedialog" class="paper_dialog">
                    <div id="addCandidate" class="paper">
                        <div class="box clearfix">
                            <h3>new candidate</h3>
                            <input type="button"  class="btn-add-trigger" value="ADD">
                            <div class="clearfix"></div>
                            <hr>
                            <div class="form-group text-center">
                                <form id="form_new_candidate" action="/" method="POST">
                                    <span id="pLogin" class="text-danger"></span>
                                    <p><input class="field" type="text" name="name" placeholder="Name"></p>

                                    <p><input class="field" type="text" name="surname" placeholder="Surname"></p>

                                    <p><input class="field" type="text" name="phone" placeholder="10 digit phone number"></p>

                                    <p><input class="field" type="text" name="email" placeholder="E-mail"></p>

                                    <p><input class="field" type="text" name="profile" placeholder="Link to summary"></p>

                                    <div class="form_input_size clearfix">
                                        <h4>Sex:</h4>

                                        <ul class="cd-form-list">
                                            <li>
                                                <input type="radio" name="sex" id="cd-radio-1" value="1" checked>
                                                <label for="cd-radio-1">male</label>
                                            </li>

                                            <li>
                                                <input type="radio" name="sex" id="cd-radio-2" value="2">
                                                <label for="cd-radio-2">female</label>
                                            </li>
                                        </ul>
                                    </div>

                                    <p><input class="field" type="number" min="14" max="90" name="age" placeholder="Age"></p>

                                    <label for="vacancy_id">Assign vacancy:</label>
                                    <select class="form-control _select" name="vacancy_id">
                                        <option value="0">None</option>
                                    </select>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title pull-left">Stored files:</h3>
                                <div class="pull-right">
                                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                    <input id="searchbox" class="" type="text" placeholder="SEARCH">
                                    <label></label>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover table-condensed">
                                    <thead>
                                    <tr>
                                        <th class="text-center"><span>Name</span></th>
                                        <th class="text-center" style="width: 8em"><span>type</span></th>
                                        <th class="text-right" style="width: 12em"><span>size</span></th>
                                        <th colspan="3"></th>
                                    </tr>
                                    </thead>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td style="width: 35px">
                                            <button class = "btn btn-sm btn_c" data-action="info" data-pid="">
                                                <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                                            </button>
                                        </td>
                                        <td style="width: 35px">
                                            <button class = "btn btn-sm btn_c" data-action="delete" data-pid="">
                                                <span class="glyphicon glyphicon glyphicon-remove" aria-hidden="true"></span>
                                            </button>
                                        </td>
                                        <td style="width: 35px">
                                            <button class = "btn btn-sm btn_c" data-action="download" data-pid="">
                                                <span class="glyphicon glyphicon-download" aria-hidden="true"></span>
                                            </button>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="slide_side right_side">
            <div id="RContainer" class="container-fluid">

            </div>
        </div>
    </div>
</div>

<script>
    $(".btn").on('click', function(){
        $("#somedialog").addClass('open');
    });
    $("#somedialog").on('click', function(e){
        if(e.target == this){
            $(this).removeClass('open');
        }
    })
</script>