<?include_once Config::LAYOUT_DIR."userInfo".Config::LAYOUT_TYPE;?>
<?=Menu::getMenu()?>
<div class="wrap">
    <div class="innerWrap">
        <div class="slide_side">
            <div id="LContainer" class="container-fluid">

<?include_once Config::LAYOUT_DIR.Router::getControllerName(0)."/events_partial".Config::LAYOUT_TYPE;?>

            </div>
        </div>
        <div class="slide_side right_side">
            <div id="RContainer" class="container-fluid">

            </div>
        </div>
    </div>
</div>