<div id="new_entry" class="paper_dialog">
    <div class="paper">
        <div class="box clearfix">
            <h3>new event</h3>
            <input type="button" id="btnAddEvent" class="btn-add-trigger" value="ADD">
            <div class="clearfix"></div>
            <h5></h5>
            <hr>
            <div class="form-group text-center">
                <form id="form_new_entry" action="/workspace/EventInterview" method="POST">
                    <span id="warnings" class="text-danger"></span>
                    <p><input class="field" type="text" name="title" placeholder="Title"></p>
                    <p><textarea class="field" name="description" placeholder="Description" rows="5"></textarea></p>
                    <label for="form_datetime">Beginning at:</label>
                    <p>
                        <input size="16" type="text" name="start" readonly class="form_datetime field">
                    </p>

                    <label for="form_datetime">End at:</label>
                    <p>
                        <input size="16" type="text" name="end" readonly class="form_datetime field">
                    </p>

                    <label for="vacancy_id">Assign vacancy:</label>
                    <select class="form-control _select" name="vacancy_id">
                        <option value="0">None</option>
                        <?=htmlselectHelper::Form($this->vacancies, 'id', 'title')?>
                    </select>

                    <label for="candidate_id">Assign candidate:</label>
                    <select class="form-control _select" name="candidate_id">
                        <option value="0">None</option>
                        <?=htmlselectHelper::Form($this->users, 'id', 'fullname')?>
                    </select>
                    <input name="event_type" value="event-interview" hidden>
                </form>
            </div>
        </div>
    </div>
</div>

<div id="show_entry" class="paper_dialog">
    <div class="paper">
        <div class="box clearfix">
            <h3 data-name="event_type"></h3>
            <a href="#" class="popupbox-close"></a>
            <div class="clearfix"></div>
            <hr>
                <table id="t_info" class="table_info">
                    <tbody>
                    <tr>
                        <td class="pad_l _hi">Title:</td>
                        <td data-name="title" colspan="3"></td>
                    </tr>
                    <tr>
                        <td class="pad_l _hi">Created:</td>
                        <td data-name="created"></td>
                    </tr>
                    <tr>
                        <td class="pad_l _hi">Event start:</td>
                        <td data-name="start"></td>
                        <td class="pad_l _hi">Event end:</td>
                        <td data-name="end"></td>
                    </tr>
                    <tr>
                        <td class="pad_l _hi">Description:</td>
                        <td data-name="description" class="text-center" rowspan="3" colspan="3">Young attractive woman.</td>
                    </tr>
                    <tr>
                    </tr>
                    <tr>
                    </tr>
                    </tbody>
                </table>
            <div id="vacancy_info">

            </div>
            <div id="candidate_info">

            </div>
            <br>
            <div class="fc-right">
                <div class="fc-button-group">
                    <button type="button" class="button_b button--size-xs">Done</button>
                    <button type="button" class="button_b button--size-xs">week</button>
                    <button type="button" class="button_b button--size-xs">remove</button>
                </div>
            </div>

        </div>
    </div>
</div>

<div class="row spacer">
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="clr">
            <div>
                <h3>Interviews <span id="interCount" class="badge badge-primary"><?=$this->interCount?></span></h3>
                <p id="s1_data"></p>
                <button id="plus_one" class="button button--rayen button--size-s mob-right" data-text="+1"><span>Add new</span></button>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="clr">
            <div>
                <h3>Hired:</h3>
                <p id="s2_data"></p>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="clr">
            <div>
                <h3>Rejected:</h3>
                <p id="sd_size"></p>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="clr">
            <div id="heap_info">
                <h3>Results:</h3>
                <p></p>
            </div>
        </div>
    </div>
</div>

<div class="row spacer">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading-pure">
                <h3 class="info">Events:</h3>
            </div>
            <div class="panel-body">
                <div id='external-events'>
                    <form class="inline-form">
                        <input type="text" value="" placeholder="Event Title..." id="event_title"/><br/>
                        <button id="event_add" class="btn btn-dark" type="button">Add Event</button>
                    </form>
                    <hr/>
                        <div id="event_box">

                        </div>
                </div>
            </div>
        </div>

    </div>

    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading-pure">
                <h3 class="info">Calendar</h3>
            </div>
            <div class="panel-body">

                <div id="fullcalendar"></div>

            </div>
        </div>
    </div>
</div>

<script>
    document.title = "Events";

    InitDateTime(".form_datetime");
    InitSlimScroll(".scroll");
    Calendar.init();
</script>