<div class="row">
    <div class="col-md-3 col-xs-6">
        <div class="clr">
            <div id="sensor1_info">
                <h3>Sensor:</h3>
                <p id="s1_data"></p>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-xs-6">
        <div class="clr">
            <div id="sensor2_info">
                <h3>Sensor:</h3>
                <p id="s2_data"></p>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-xs-6">
        <div class="clr">
            <div id="card_info">
                <h3><span class="glyphicon glyphicon-hdd"></span> Card info:</h3>
                <p id="sd_size"></p>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-xs-6">
        <div class="clr">
            <div id="heap_info">
                <h3><span class="glyphicon glyphicon-dashboard"></span> Free heap:</h3>
                <p id="heap_size"></p>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title pull-left">Stored files:</h3>
                <div class="pull-right">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    <input id="searchbox" class="" type="text" placeholder="SEARCH">
                    <label></label>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="table-responsive">
                <table class="table table-bordered table-striped table-hover table-condensed">
                    <thead>
                    <tr>
                        <th class="text-center"><span>Name</span></th>
                        <th class="text-center" style="width: 8em"><span>type</span></th>
                        <th class="text-right" style="width: 12em"><span>size</span></th>
                        <th colspan="3"></th>
                    </tr>
                    </thead>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td style="width: 35px">
                        <button class = "btn btn-sm btn_c" data-action="info" data-pid="">
                            <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                        </button>
                    </td>
                    <td style="width: 35px">
                        <button class = "btn btn-sm btn_c" data-action="delete" data-pid="">
                            <span class="glyphicon glyphicon glyphicon-remove" aria-hidden="true"></span>
                        </button>
                    </td>
                    <td style="width: 35px">
                        <button class = "btn btn-sm btn_c" data-action="download" data-pid="">
                            <span class="glyphicon glyphicon-download" aria-hidden="true"></span>
                        </button>
                    </td>
                </table>
            </div>
        </div>
    </div>
</div>