<div id="new_entry" class="paper_dialog">
    <div class="paper">
        <div class="box clearfix">
            <h3>new event</h3>
            <input type="button" id="btnAdd" class="btn-add-trigger" value="ADD">
            <div class="clearfix"></div>
            <hr>
            <div class="form-group text-center">
                <form id="form_new_entry" action="/workspace/Events" method="POST">
                    <span id="warnings" class="text-danger"></span>
                    <p><input class="field" type="text" name="title" placeholder="Title"></p>
                    <p><textarea class="field" name="description" placeholder="Description" rows="5"></textarea></p>
                    <label for="form_datetime">Beginning at:</label>
                    <p>
                        <input size="16" type="text" name="start" readonly class="form_datetime field">
                    </p>

                    <label for="form_datetime">End at:</label>
                    <p>
                        <input size="16" type="text" name="end" readonly class="form_datetime field">
                    </p>

                    <label for="vacancy_id">Assign vacancy:</label>
                    <select class="form-control _select" name="vacancy_id">
                        <option value="0">None</option>
                        <?=htmlselectHelper::Form($this->vacancies, 'id', 'title')?>
                    </select>

                    <label for="candidate_id">Assign candidate:</label>
                    <select class="form-control _select" name="candidate_id">
                        <option value="0">None</option>
                        <?=htmlselectHelper::Form($this->users, 'id', 'fullname')?>
                    </select>
                    <input name="event_type" value="event-interview" hidden>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="clr">
            <div>
                <h3>Interviews</h3>
                <p id="s1_data"></p>
                <button id="plus_one" class="button button--rayen button--size-s" data-text="+1"><span>Add new</span></button>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="clr">
            <div>
                <h3>Hired:</h3>
                <p id="s2_data"></p>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="clr">
            <div>
                <h3>Rejected:</h3>
                <p id="sd_size"></p>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="clr">
            <div id="heap_info">
                <h3>Results:</h3>
                <p></p>
            </div>
        </div>
    </div>
</div>

    <div class="row spacer">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading-pure">
                <h3 class="info">Events:</h3>
            </div>
            <div class="panel-body">

            </div>
        </div>
        
    </div>

    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading-pure">
                <h3 class="info">Calendar</h3>
            </div>
            <div class="panel-body">

                <div class="panel-heading clean clearfix text-center">
                    <div class="btn-group pull-left">
                        <button class="button button--material button--size-xs btn-sm" data-calendar-nav="prev">&lt;< Prev</button>
                        <button class="button button--material button--size-xs" data-calendar-nav="today">Today</button>
                        <button class="button button--material button--size-xs" data-calendar-nav="next">Next >&gt;</button>
                    </div>
                    <b class="calender-title"></b>
                    <div class="btn-group pull-right">
                        <button class="button button--material button--size-xs" data-calendar-view="year">Year</button>
                        <button class="button button--material button--size-xs active" data-calendar-view="month">Month</button>
                        <button class="button button--material button--size-xs" data-calendar-view="week">Week</button>
                        <button class="button button--material button--size-xs" data-calendar-view="day">Day</button>
                    </div>
                </div><!--<div class="panel-heading clean clearfix text-center">
                    <div class="btn-group pull-left">
                        <button class="btn btn-default btn-sm" data-calendar-nav="prev">&lt;< Prev</button>
                        <button class="btn btn-sm btn-default" data-calendar-nav="today">Today</button>
                        <button class="btn btn-sm btn-default" data-calendar-nav="next">Next >&gt;</button>
                    </div>
                    <b class="calender-title"></b>
                    <div class="btn-group pull-right">
                        <button class="btn btn-sm btn-default" data-calendar-view="year">Year</button>
                        <button class="btn btn-sm btn-default active" data-calendar-view="month">Month</button>
                        <button class="btn btn-sm btn-default" data-calendar-view="week">Week</button>
                        <button class="btn btn-sm btn-default" data-calendar-view="day">Day</button>
                    </div>
                </div>-->

                <div id="calendar"></div>

            </div>
        </div>
    </div>
</div>

    <div class="row spacer">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading-pure">
                <h3 class="info">Events:</h3>
            </div>
            <div class="panel-body">

            </div>
        </div>

    </div>

    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading-pure">
                <h3 class="info">Calendar</h3>
            </div>
            <div class="panel-body">

                <div id="fullcalendar"></div>

            </div>
        </div>
    </div>
</div>

<script>
    document.title = "Events";

    $(".form_datetime").datetimepicker({
        format: "dd-MM-yyyy hh:ii",
        autoclose: true,
        todayBtn: true,
        minuteStep: 10
    });

    $('#fullcalendar').fullCalendar({
        events: '/workspace/Feed',
        firstDay: 1,
        fixedWeekCount: false,
        aspectRatio: 3,
        contentHeight: 506,
        header: {
            left: 'prev,today,next',
            center: 'title',
            right: 'month,basicWeek,agendaDay'
        }
    });

    (function($) {

        "use strict";

        var options = {
            events_source: '/workspace/Feed',
            view: 'month',
            tmpl_cache: false,
            onAfterEventsLoad: function(events) {
                if(!events) {
                    return;
                }
                var list = $('#eventlist');
                list.html('');

                $.each(events, function(key, val) {
                    $(document.createElement('li'))
                        .html('<a href="' + val.url + '">' + val.title + '</a>')
                        .appendTo(list);
                });
            },
            onAfterViewLoad: function(view) {
                $('.calender-title').text(this.getTitle());
                $('.btn-group button').removeClass('active');
                $('button[data-calendar-view="' + view + '"]').addClass('active');
            },
            classes: {
                months: {
                    general: 'label'
                }
            }
        };

        var calendar = $('#calendar').calendar(options);

        $('.btn-group button[data-calendar-nav]').each(function() {
            var $this = $(this);
            $this.click(function() {
                calendar.navigate($this.data('calendar-nav'));
            });
        });

        $('.btn-group button[data-calendar-view]').each(function() {
            var $this = $(this);
            $this.click(function() {
                calendar.view($this.data('calendar-view'));
            });
        });

        $('#first_day').change(function(){
            var value = $(this).val();
            value = value.length ? parseInt(value) : null;
            calendar.setOptions({first_day: value});
            calendar.view();
        });

        $('#language').change(function(){
            calendar.setLanguage($(this).val());
            calendar.view();
        });

        $('#events-in-modal').change(function(){
            var val = $(this).is(':checked') ? $(this).val() : null;
            calendar.setOptions({modal: val});
        });
        $('#events-modal .modal-header, #events-modal .modal-footer').click(function(e){
            //e.preventDefault();
            //e.stopPropagation();
        });



        $('.add-calendar-event').click(function(){

            var calendarEventName = $('.calendar-event-name').val();

            var dateTime = new Date();

            var hr = dateTime.getHours();
            var mins = dateTime.getMinutes();

            if(calendarEventName == ''){
                alert('Event name can’t be blank')
            }

            else{
                $('.calendar-events-ctrl').before('\
							<h5 class="no-margn"><a href="#" class="text-muted"><strong>'+calendarEventName+'</strong></a></h5>\
                            <p><small>at '+hr+':'+mins+'</small></p>\
                            <hr>')
            }
        });
    }(jQuery));

</script>
<script type="text/javascript">
    $(function(){
        $("document").slimScroll({
            size: '8px',
            width: '100%',
            height: '100%',
            color: '#ff4800',
            allowPageScroll: true,
            alwaysVisible: true
        });
    });
</script>