<h2 class="info">Vacancies <span class="badge badge-primary"><?=$this->vCount;?></span></h2>

<div id="new_entry" class="paper_dialog">
    <div id="addCandidate" class="paper">
        <div class="box clearfix">
            <h3>new vacancy</h3>
            <input type="button" id="btnAdd" class="btn-add-trigger" value="ADD">
            <div class="clearfix"></div>
            <h5></h5>
            <hr>
            <div class="form-group text-center">
                <form id="form_new_entry" action="/workspace/AddVacancy" method="POST">
                    <span id="warnings" class="text-danger"></span>
                    <p><input class="field" type="text" name="title" placeholder="Title" maxlength="40"></p>

                    <p><textarea class="field" name="description" placeholder="Description" rows="5"></textarea></p>

                    <label for="vacancy_id">Assign candidate:</label>
                    <select class="form-control _select" name="candidate_id">
                        <option value="0">None</option>
                        <?=htmlselectHelper::Form($this->users, 'id', 'fullname')?>
                    </select>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row spacer">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading-pure">
                <button id="plus_one" class="button button--rayen button--size-s" data-text="+1"><span>Add new</span></button>
                <div class="pull-right">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    <input id="searchbox" class="" type="text" placeholder="SEARCH">
                    <label></label>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="table-responsive">
                <table id="fvacancies" class="table table-bordered table-hover table-condensed"
                       data-del-ref="/workspace/DeleteVacancy"
                       data-info-ref="/workspace/VacancyInfo">
                    <thead>
                    <tr>
                        <th class="text-center"><span>№</span></th>
                        <th class="text-center"><span>Title</span></th>
                        <th class="text-center"><span>Description</span></th>
                        <th class="text-center"><span>Date added</span></th>
                        <th class="text-center"><span>Assigned</span></th>
                        <th class="text-center"><span>State</span></th>
                        <th colspan="2"></th>
                    </tr>
                    </thead>
                    <tbody>
<?php
                    foreach ($this->vacancies as  $vacancy):
?>
                        <tr>
                            <td><?=$vacancy->N?></td>
                            <td><?=$vacancy->title?></td>
                            <td><?=$vacancy->description?></td>
                            <td><?=$vacancy->date_added?></td>
                            <td><?=$vacancy->assigned?></td>
                            <td><?=$vacancy->state ? "Open" : "Closed"?></td>
                            <td>
                                <button id="<?=$vacancy->id?>" class="btn btn-sm btn_c" data-action="info">
                                    <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                                </button>
                            </td>
                            <td>
                                <button id="<?=$vacancy->id?>" class="btn btn-sm btn_c" data-action="delete">
                                    <span class="glyphicon glyphicon glyphicon-remove" aria-hidden="true"></span>
                                </button>
                            </td>
                        </tr>
<?php
                    endforeach;
?>
                    </tbody>
                </table>
            </div>
            <?=popupboxHelper::Form("delBox")?>
            <?= paginationHelper::Form($this->vCount, "/workspace/Vacancies");?>
        </div>
    </div>
</div>

<script>
    document.title = "Vacancies";
</script>