<?include_once Config::LAYOUT_DIR."userInfo".Config::LAYOUT_TYPE;?>
<?=Menu::getMenu()?>
<div class="wrap">
    <div class="innerWrap">
        <div class="slide_side">
            <div id="LContainer" class="container-fluid">

                <h2 class="info">Vacancies <span class="badge badge-primary">0</span></h2>

                <div id="new_vac" class="paper_dialog">
                    <div id="addCandidate" class="paper">
                        <div class="box clearfix">
                            <h3>new vacancy</h3>
                            <input type="button"  class="btn-add-trigger" value="ADD">
                            <div class="clearfix"></div>
                            <hr>
                            <div class="form-group text-center">
                                <form id="form_new_vacancy" action="/workspace/Vacancies" method="POST">
                                    <span id="warnings" class="text-danger"></span>
                                    <p><input class="field" type="text" name="title" placeholder="Title"></p>

                                    <p><input class="field" type="text" name="description" placeholder="Description"></p>

                                    <label for="vacancy_id">Assign candidate:</label>
                                    <select class="form-control _select" name="user_id">
                                        <option value="0">None</option>
                                        <?=htmlselectHelper::Form($this->users)?>
                                    </select>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <button id="plus_one" class="button button--rayen button--size-s" data-text="+1"><span>Add new</span></button>
                                <div class="pull-right">
                                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                    <input id="searchbox" class="" type="text" placeholder="SEARCH">
                                    <label></label>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <div class="table-responsive">
                                <table id="fvacancies" class="table table-bordered table-striped table-hover table-condensed">
                                    <thead>
                                    <tr>
                                        <th class="text-center"><span>Title</span></th>
                                        <th class="text-center"><span>Description</span></th>
                                        <th class="text-center"><span>Date added</span></th>
                                        <th class="text-center"><span>Assigned</span></th>
                                        <th colspan="2"></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td>
                                            <button class = "btn btn-sm btn_c" data-action="info" data-pid="">
                                                <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                                            </button>
                                        </td>
                                        <td>
                                            <button class = "btn btn-sm btn_c" data-action="delete" data-pid="">
                                                <span class="glyphicon glyphicon glyphicon-remove" aria-hidden="true"></span>
                                            </button>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="slide_side right_side">
            <div id="RContainer" class="container-fluid">

            </div>
        </div>
    </div>
</div>

<script>
    $("#plus_one").on('click', function(){
        $("#new_vac").addClass('open');
    });
    $("#new_vac").on('click', function(e){
        if(e.target == this){
            $(this).removeClass('open');
        }
    })
</script>