<div class="container-fluid">
    <div id="Candidate_info">
        <h2 class="info"><?=$this->vacancy->title?></h2>

        <?if(isset($_GET['ajax'])):?>
            <button id="goBack" class="button button--rect button--size-m">
                <span class="fc-icon fc-icon-left-single-arrow"></span><span>Back to list</span>
            </button>
        <?endif;?>

    </div>

    <div class="row spacer">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading-pure">
                    <h4 class="header text-center">Vacancy info:</h4>

                    <div class="pull-right">
                        <button id="btn_edit" class="button button--rayen button--size-s" data-text="Edit"><span class="glyphicon glyphicon-edit"></span></button>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <table id="t_info">
                    <tbody>
                    <tr>
                        <td class="pad_l _hi">Title:</td>
                        <td data-name="title"><?=$this->vacancy->title?></td>
                    </tr>
                    <tr>
                        <td class="pad_l _hi">Created:</td>
                        <td data-name="date_added"><?=$this->vacancy->date_added?></td>
                        <td class="pad_l _hi">State:</td>
                        <td data-name="state"><?=$this->vacancy->state == 1 ? "Opened":"Closed"?></td>
                    </tr>
                    <tr>
                        <td class="pad_l _hi" >Description:</td>
                        <td data-name="description" class="text-center" rowspan="3" colspan="3"><?=$this->vacancy->description?></td>
                    </tr>
                    <tr>
                    </tr>
                    <tr>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading-pure">
                    <h4 class="header text-center">Assigned candidates:</h4>
                    <div class="pull-right">
                        <button  class="button button--rayen button--size-s" data-text="+1"><span>Add new</span></button>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="scroll" data-height="220">
                    <ul>
                        <?php
                        foreach ($this->assignedCandidates as $c):
                            ?>
                            <li>
                                <ul>
                                    <li><?=$c->N?></li>
                                    <li><?=$c->fullname?></li>
                                    <li><?=$c->email?></li>
                                    <li><?=$c->phone?></li>
                                    <li><?=$c->assigned?></li>
                                </ul>
                            </li>
                            <?php
                        endforeach;
                        ?>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading-pure">
                    <h4 class="header text-center">Timeline</h4>
                    <div class="clearfix"></div>
                </div>
                date_added
            </div>
        </div>
    </div>

    <div id="edit_entry" class="paper_dialog">
        <div id="editVacancy" class="paper">
            <div class="box clearfix">
                <h3>Edit</h3>
                <input type="button" id="btnSaveVac" class="btn-add-trigger" value="Save">
                <div class="clearfix"></div>
                <h5></h5>
                <hr>
                <div class="form-group text-center">
                    <form id="form_edit_entry" name="editVac" action="/workspace/EditVacancy">
                        <span id="warnings" class="text-danger"></span>
                        <div class="paper_label">
                            <span>Title</span>
                        </div>
                        <p><input class="field" type="text" name="title" placeholder="Title" maxlength="40" value="<?=$this->vacancy->title?>"></p>
                        <div class="paper_label">
                            <span>Description</span>
                        </div>
                        <p>
                            <textarea class="field" name="description" placeholder="Description" rows="5"><?=$this->vacancy->description?></textarea>
                        </p>

                        <div class="paper_label">
                            <span>State</span>
                        </div>
                        <div class="switch">
                            <input name="state" id="sw-toggle-1" class="sw-toggle sw-toggle-sq <?=$this->vacancy->state ? "checked":""?>" type="checkbox" <?=$this->vacancy->state ? "checked":""?>>
                            <label for="sw-toggle-1"></label>
                        </div>
                        <input name="id" value="<?=$this->vacancy->id?>" hidden>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        document.title = "Vacancy <?=$this->vacancy->title?>";
    </script>
</div>
