 <div class="panel-heading">
        <h3 class="panel-title pull-left"><?=$this->heading?></h3>
     <div class="in_wrapper pull-right">
         <span class="pull-left glyphicon glyphicon-search"></span>
         <input id="searchbox" data-action="Super/GetAllUsers/0" class="searchField"
                type="text" value="<?if(isset($this->search)) echo $this->search?>">
         <label></label>
     </div>
     <div class="switch pull-right">
         <span class="pull-left">Лише авторизовані </span>
         <input id="sw-toggle-1" data-key="<?=Filter::ONLY_AUTHORIZED?>" data-action="super/SetParam/" data-postaction="Super/GetAllUsers/0" class="sw-toggle sw-toggle-sq <?=Filter::Check()?>" type="checkbox" <?=Filter::Check()?>>
         <label for="sw-toggle-1"></label>
     </div>
     <div class="clearfix"></div>
</div>
    <div id="conTable" class="table-responsive">
        <table class="table table-bordered table-striped table-hover table-condensed">
            <thead>
            <tr>
                <th class="text-center" style="width: 40px">#ID</th>
                <th class="text-center"><span>Логін</span></th>
                <th class="text-center"><span>П.І.Б</span></th>
                <th class="text-center"><span>E-Mail</span></th>
                <th class="text-center"><span>ТУ</span></th>
                <th class="text-center"><span>Інспекція</span></th>
                <th class="text-center"><span>Посада</span></th>
                <th colspan="3"></th>
            </tr>
            </thead>
        <?php
        $int=0;
        foreach ($this->users as  $user):
        if(++$int % 2 === 0){
            echo '<tr class="active">';
        }
        else{
            echo '<tr>';
        }
        foreach ($user as $key => $value):
            if($value === NULL || $key == 'permissionID')
                continue;
?>
            <td data-field="<?=$key?>"><?=$value?></td>
<?
        endforeach;
?>
        <td style="width: 35px">
            <button class = "btn btn-info btn-xs" id="<?=$user->UserID?>" data-toggle="tooltip" data-placement="top" title="інформація" data-pid="<?=$user->permissionID?>">
                <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
            </button>
        </td>
        <td style="width: 35px">
            <button class = "btn btn-danger btn-xs" id="<?=$user->UserID?>" data-toggle="tooltip" data-placement="top" title="видалити користувача" data-action="delete" data-pid="<?=$user->permissionID?>">
                <span class="glyphicon glyphicon glyphicon-remove" aria-hidden="true"></span>
            </button>
        </td>
        <td>
            <button class="btn btn-warning btn-xs" id="<?=$user->UserID?>" data-toggle="tooltip" data-placement="top" title="редагувати користувача" data-pid="<?=$user->permissionID?>">ред.
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
            </button>
        </td>
<?php
endforeach;
?>
        </table>
    </div>
<?=paginationHelper::Form($this->nUserCount, "super/GetAllUsers");