<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link href="<?=@Config::STYLES_DIR?>styles.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>

    <link rel="stylesheet" type="text/css" href="assets/DataTables/datatables.css">
    <script type="text/javascript" charset="utf8" src="assets/DataTables/datatables.js"></script>

</head>
<body>

</body>
</html>
<script>
    $(document).ready( function () {
        $('#table_id').DataTable();
    } );
</script>
