<div class="panel-heading">
    <h3 class="panel-title pull-left"><?=$this->heading?></h3>

    <button type="button" id="bAdd" class="btn_square btn btn-info pull-right">Додати</button>
    <div class="in_wrapper pull-right">
        <span class="pull-left glyphicon glyphicon-search"></span>
        <input id="searchbox" data-action="workspace/LoadMyEntitys/0" class="searchField"
               type="text" value="<?if(isset($this->search)) echo $this->search?>">
        <label></label>
    </div>
    <div class="clearfix"></div>
</div>
<div id="conTable" class="table-responsive">
    <table class="table table-bordered table-striped table-hover table-condensed">
        <thead>
            <tr>
    <th class="text-center" style="width: 40px">№</th>
    <th class="text-center col-sm-3 col-lg-2"><span>ЄДРПОУ</span></th>
    <th class="text-center"><span>Назва</span></th>
    <th class="text-center"><span>П.І.Б</span></th>
    <th class="text-center"><span>Адреса(фак.)</span></th>
    <th colspan="2"></th>
            </tr>
        </thead>
<?
$int=0;
foreach ($this->myco as  $entity):
    if(++$int % 2 === 0){
        echo '<tr class="active">';
    }
    else{
        echo '<tr>';
    }
    foreach ($entity as $key => $value):
        if($value === NULL || $key == 'permissionID')
            continue;
        ?>
        <td><?=$value?></td>
        <?
    endforeach;
?>
    <td style="width: 35px">
        <button class="btn btn-info btn-xs" id="<?=$entity['Entity_EDRPOU']?>">
            <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
        </button>
    </td>
    <td>
        <button class="btn btn-warning btn-xs" id="<?=$entity['Entity_EDRPOU']?>">ред.<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
        </button>
    </td>
<?
endforeach;
?>
    </table>
</div>
<?php echo paginationHelper::Form($this->numRows, "workspace/LoadMyEntitys")?>