<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?=$this->_title?></title>
    <!--<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">-->    <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed&subset=latin,cyrillic' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/assets/DataTables/datatables.css">
    <link rel="stylesheet" type="text/css" href="<?=@Config::STYLES_DIR?>bootstrap-tagsinput.css">
    <link href="<?=@Config::STYLES_DIR?>styles.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>-->
    <script src="/js/bootstrap.min.js"></script>
    <script src="<?=@Config::JAVAScripts_DIR?>bootstrap-tagsinput.min.js"></script>
    <script type="text/javascript" charset="utf8" src="/assets/DataTables/datatables.js"></script>
    <script src="<?=@Config::JAVAScripts_DIR?>scripts.js"></script>
</head>
<body>
<div class="topLeftCenter"></div>
<?
include_once Config::LAYOUT_DIR."loadingOverlay".Config::LAYOUT_TYPE;
include_once $this->_page_content;
?>
</body>
<?include_once Config::LAYOUT_DIR."footer".Config::LAYOUT_TYPE;?>
</html>