<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?=$this->_title?></title>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed&subset=latin,cyrillic' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="/assets/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="<?=@Config::STYLES_DIR?>bootstrap-tagsinput.css">
    <link href="<?=@Config::STYLES_DIR?>calendar.css" rel="stylesheet">
    <link href="<?=@Config::STYLES_DIR?>bootstrap-datetimepicker.min.css" rel="stylesheet">
    <link href="<?=@Config::STYLES_DIR?>fullcalendar.css" rel="stylesheet">
    <link href="<?=@Config::STYLES_DIR?>app/styles.css" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="<?=@Config::JAVAScripts_DIR?>bootstrap.min.js"></script>
    <script src="<?=@Config::JAVAScripts_DIR?>underscore-min.js"></script>
    <script src="<?=@Config::JAVAScripts_DIR?>calendar.js"></script>
    <script src="<?=@Config::JAVAScripts_DIR?>bootstrap-datetimepicker.min.js"></script>

    <script src="<?=@Config::JAVAScripts_DIR?>moment.min.js"></script>
    <script src="<?=@Config::JAVAScripts_DIR?>fullcalendar.min.js"></script>
    <script src="<?=@Config::JAVAScripts_DIR?>jquery.slimscroll.min.js"></script>
    <script src="<?=@Config::JAVAScripts_DIR?>scripts.js"></script>
</head>
<body>
<div class="topLeftCenter"></div>
<?
include_once Config::LAYOUT_DIR."loadingOverlay".Config::LAYOUT_TYPE;
include_once $this->_page_content;
?>
</body>
<?include_once Config::LAYOUT_DIR."footer".Config::LAYOUT_TYPE;?>
</html>