<div class="rMain">
    <div class="container">
        <div class="row">
            <div class="hidden-xs col-sm-3"></div>
            <div class="col-xs-12 col-sm-6">
                <?php $this->GetSuccess();?>
                <?=$this->GetError('validator', true);?>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Заява на реєстрацію</h3>
                        <hr>
                        <div class="form-group text-center">
                            <form id="freg" action="/register" method="POST">
                                <span id="pLogin" class="text-danger"></span>
                            <p><input class="field" type="text" name="tLogin" id="tL" placeholder="  Ім'я користувача"
                                      value="<?= ($_POST['tLogin'])?$_POST['tLogin']:''?>"></p>
                            <p><input data-toggle="tooltip" data-placement="right" class="field" type="password" id="tPass" placeholder="  Пароль">
                                <span id="passInfo" class="text-danger"></span></p>

                            <div class="form-group has-error has-feedback">
                                <input class="field" type="password" id="tPassConf" placeholder="  Підтвердіть пароль">
                                <span id="passInfoConf" class="text-danger"></span>
                            </div>

                            <p><input class="field pib" type="text" name="tPib" placeholder="  ПІБ"
                                      value="<?= ($_POST['tPib'])?$_POST['tPib']:''?>"></p>
                            <p><input class="field" type="text" id="tMail" name="tMail" placeholder="  електронна адреса"
                                      value="<?= ($_POST['tMail'])?$_POST['tMail']:''?>"><span id="pMail" class="text-danger"></span></p>

                            <div class="form-group">
                                <label for="sTU">Територіальне управління:</label>
                                <select class="form-control selectWidth registerSelect" id="sTU" name="sTU" onchange="showInspections(this.value)">
                                    <option value="0">Оберіть ТУ</option>
                                    <?=htmlselectHelper::Form($this->territory)?>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="sIns">Інспекція:</label>
                                <select class="form-control selectWidth registerSelect" id="sIns" name="sIns">

                                </select>
                            </div>

                            <div class="form-group">
                                <label for="sJob">Посада:</label>
                                <select class="form-control selectWidth registerSelect" id="sJob" name="sJob">
                                    <?=htmlselectHelper::Form($this->jobs, 'admin')?>
                                </select>
                            </div>
                            <hr>
                            <input type="button" name="bSubmit"  class="my btn btn-primary" onclick="SubForm(this.form)" value="Подати заяву">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="hidden-xs col-sm-3"></div>
        </div>
    </div>

    <script src='/js/jscripts.js'></script>
    <script>
        document.getElementById("tMail").addEventListener('blur', CheckEmail);
        document.getElementById("tPass").addEventListener("keyup", CheckPassword);
        document.getElementById("tPassConf").addEventListener("change", CheckPassword);
        document.getElementById("tL").addEventListener('blur', CheckLogin);
    </script>
    <script src="http://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/md5.js"></script>